import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    welcome: "Welcome",
    dashboard: "Dashboard",
    chat: "Chat",
    newChat: "New Chat",
    chatHistory: "Chat History",
    settings: "Settings",
    profile: "Profile",
    notifications: "Notifications",
    plans: "Plans",
    subscription: "Subscription",
    logout: "Logout",
    credits: "Credits",
    questionsLeft: "Questions Left",
    used: "Used",
    available: "Available",
    sendMessage: "Send message...",
    typeMessage: "Type your message here...",
    businessSetup: "Business Setup",
    marketAnalysis: "Market Analysis",
    marketingStrategy: "Marketing Strategy",
    contentGenerator: "Content Generator",
    analytics: "Analytics & Reports",
    optimization: "Optimization",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    users: "Users",
    payments: "Payments",
    activityLogs: "Activity Logs",
    totalUsers: "Total Users",
    totalPayments: "Total Payments",
    managePlans: "Manage Plans",
    addPlan: "Add Plan",
    editPlan: "Edit Plan",
    planName: "Plan Name",
    price: "Price",
    creditsIncluded: "Credits Included",
    tokensPerQuestion: "Tokens Per Question",
    features: "Features",
    monthly: "Monthly",
    yearly: "Yearly",
    subscribe: "Subscribe",
    currentPlan: "Current Plan",
    noPlan: "No Active Plan",
    upgradeNow: "Upgrade Now",
    welcomeMessage: "Welcome to our platform! You have received 10 free credits.",
    subscriptionSuccess: "Subscription successful!",
    youSubscribedTo: "You have subscribed to",
    businessName: "Business Name",
    businessType: "Business Type",
    industry: "Industry",
    country: "Country",
    city: "City",
    companySize: "Company Size",
    website: "Website",
    socialPlatforms: "Social Platforms",
    currentChallenges: "Current Challenges",
    goals: "Goals",
    monthlyBudget: "Monthly Budget",
    targetAudience: "Target Audience",
    competitors: "Competitors",
    saveProfile: "Save Profile",
    adminPanel: "Admin Panel",
    home: "Home",
    chatbai: "ChatBAI",
    howItWorks: "How It Works",
    pricing: "Pricing",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    phone: "Phone",
    birthDate: "Birth Date",
    gender: "Gender",
    male: "Male",
    female: "Female",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signIn: "Sign In",
    signUp: "Sign Up",
    getStarted: "Get Started",
    aiPowered: "AI-Powered Business Intelligence",
    heroSubtitle: "Transform your business with intelligent market analysis, marketing strategies, and content generation - all powered by advanced AI.",
    freeCredits: "Free Credits",
    questions: "Questions",
    reviewUs: "Review Us",
    submitReview: "Submit Review",
    yourRating: "Your Rating",
    yourReview: "Your Review",
    yourName: "Your Name",
    yourJobTitle: "Your Job Title",
    clientTestimonials: "Client Testimonials",
    reviewSubmitted: "Review submitted successfully!",
    next: "Next",
    previous: "Previous",
    skip: "Skip",
    finish: "Finish"
  },
  ar: {
    welcome: "مرحباً",
    dashboard: "لوحة التحكم",
    chat: "المحادثة",
    newChat: "محادثة جديدة",
    chatHistory: "سجل المحادثات",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
    plans: "الباقات",
    subscription: "الاشتراك",
    logout: "تسجيل الخروج",
    credits: "النقاط",
    questionsLeft: "الأسئلة المتبقية",
    used: "مستخدم",
    available: "متاح",
    sendMessage: "أرسل رسالة...",
    typeMessage: "اكتب رسالتك هنا...",
    businessSetup: "إعداد النشاط التجاري",
    marketAnalysis: "تحليل السوق",
    marketingStrategy: "استراتيجية التسويق",
    contentGenerator: "توليد المحتوى",
    analytics: "التقارير والتحليلات",
    optimization: "التحسين",
    darkMode: "الوضع الليلي",
    lightMode: "الوضع النهاري",
    language: "اللغة",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    add: "إضافة",
    users: "المستخدمين",
    payments: "المدفوعات",
    activityLogs: "سجل النشاطات",
    totalUsers: "إجمالي المستخدمين",
    totalPayments: "إجمالي المدفوعات",
    managePlans: "إدارة الباقات",
    addPlan: "إضافة باقة",
    editPlan: "تعديل باقة",
    planName: "اسم الباقة",
    price: "السعر",
    creditsIncluded: "النقاط المتضمنة",
    tokensPerQuestion: "التوكنز لكل سؤال",
    features: "المميزات",
    monthly: "شهري",
    yearly: "سنوي",
    subscribe: "اشترك",
    currentPlan: "الباقة الحالية",
    noPlan: "لا يوجد اشتراك نشط",
    upgradeNow: "ترقية الآن",
    welcomeMessage: "مرحباً بك في منصتنا! لقد حصلت على 10 نقاط مجانية.",
    subscriptionSuccess: "تم الاشتراك بنجاح!",
    youSubscribedTo: "لقد اشتركت في",
    businessName: "اسم النشاط التجاري",
    businessType: "نوع النشاط",
    industry: "المجال",
    country: "الدولة",
    city: "المدينة",
    companySize: "حجم الشركة",
    website: "الموقع الإلكتروني",
    socialPlatforms: "منصات التواصل",
    currentChallenges: "التحديات الحالية",
    goals: "الأهداف",
    monthlyBudget: "الميزانية الشهرية",
    targetAudience: "الجمهور المستهدف",
    competitors: "المنافسين",
    saveProfile: "حفظ الملف",
    adminPanel: "لوحة الإدارة",
    home: "الرئيسية",
    chatbai: "ChatBAI",
    howItWorks: "كيف يعمل",
    pricing: "الأسعار",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    fullName: "الاسم الكامل",
    phone: "الهاتف",
    birthDate: "تاريخ الميلاد",
    gender: "النوع",
    male: "ذكر",
    female: "أنثى",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    getStarted: "ابدأ الآن",
    aiPowered: "ذكاء اصطناعي لإدارة الأعمال",
    heroSubtitle: "حوّل عملك مع تحليل السوق الذكي واستراتيجيات التسويق وتوليد المحتوى - كل ذلك مدعوم بالذكاء الاصطناعي المتقدم.",
    freeCredits: "نقاط مجانية",
    questions: "أسئلة",
    reviewUs: "تقييمنا",
    submitReview: "إرسال التقييم",
    yourRating: "تقييمك",
    yourReview: "رأيك",
    yourName: "اسمك",
    yourJobTitle: "وظيفتك",
    clientTestimonials: "آراء العملاء",
    reviewSubmitted: "تم إرسال التقييم بنجاح!",
    next: "التالي",
    previous: "السابق",
    skip: "تخطي",
    finish: "إنهاء"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved) setLanguage(saved);
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isRtl: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);